import AppKit
import Foundation

/// Human keyboard/pointer activity invalidates an Assistant input transaction.
/// Events generated by this process are excluded; Remote Assist explicitly marks
/// its user input so that a phone gesture also takes precedence.
@MainActor
final class MacAssistantInteractionGate {
  static let shared = MacAssistantInteractionGate()
  private(set) var generation: UInt64 = 0
  private var lastInput = Date.distantPast
  private var globalMonitor: Any?
  private var localMonitor: Any?
  init(observe: Bool = true) {
    guard observe else { return }
    let mask: NSEvent.EventTypeMask = [.keyDown, .leftMouseDown, .rightMouseDown, .scrollWheel]
    globalMonitor = NSEvent.addGlobalMonitorForEvents(matching: mask) { [weak self] event in
      let pid = event.cgEvent?.getIntegerValueField(.eventSourceUnixProcessID)
      guard pid != Int64(getpid()) else { return }
      Task { @MainActor [weak self] in self?.noteManualInput() }
    }
    localMonitor = NSEvent.addLocalMonitorForEvents(matching: mask) { [weak self] event in
      if event.cgEvent?.getIntegerValueField(.eventSourceUnixProcessID) != Int64(getpid()) {
        self?.noteManualInput()
      }
      return event
    }
  }
  func noteManualInput() {
    generation &+= 1
    lastInput = Date()
  }
  func ticket() throws -> UInt64 {
    guard Date().timeIntervalSince(lastInput) > 0.6 else {
      throw MacAssistantDeferred(message: "Waiting for your keyboard or pointer input to finish.")
    }
    return generation
  }
  func isCurrent(_ ticket: UInt64) -> Bool { ticket == generation }
}
